apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-caching-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: caching_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: |
            min without (job, instance, namespace, service, endpoint, pod) (
              squid_up{namespace="proxy", service="squid"}
            )
